### ISSUE TITLE
Widescreen Resolution

### ISSUE THREAD

**Issue by daphonk** [mck-9061/CATS#10]
Hi,

it would be nice to support 2560x1080 resolution.

Have a nice day.

**Comment by mck-9061** [comment]
As of now, there are no plans to implement this as I have no way of testing it properly.

It may be considered in the future if there's enough demand for it. For now, you can set your monitor to run at a 16:9 resolution.

**Comment by daphonk** [comment]
Do you have a hint where in the code I can do changes to fit it to my resolution myself ?

**Comment by mck-9061** [comment]
Have a look in `main.py` and `screenreader.py`. You'll need to change the coordinates of where the mouse clicks in the galaxy map and the coordinates of the box containing the jump time in the carrier management screen.

**Comment by daphonk** [comment]
Found it, and I totally agree with the text in the main.py writing it as a script is my favourite writing, too makes it much easier to understand.

For your information, the mouseclicking part works out of the box, because on my resolution only expands the galaxymap behind the controls, which seems to be at the same position as on 1080p

so I only have to get the jumptime part working
