### ISSUE TITLE
Starting Point

### ISSUE THREAD

**Issue by daphonk** [mck-9061/CATS#11]
Hi, 

if I select a other starting point from the dropdown menu, CATS ignores that and uses the first in the list.

As an example: My first point is Sol and the second point is Maia. If I select starting point directly as Sol, Cats navigates to Sol not to Maia.

Same if I select Maia es starting point, navigates to Sol, too

I have to remove Sol from the list.

**Comment by mck-9061** [comment]
Remember to press "save all settings" at the top after changing this, as mentioned in the README.
