### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by nyenyon** [mck-9061/CATS#16]
Hi,

i'm running Version 1.4.1 with EDO latest Update. Recently i always get this message:

![image](https://github.com/mck-9061/CATS/assets/137694071/015d2fed-8acc-4f93-9b6f-1f7be33ab07f)

Screen resolution: 1920x1080
webhook_url=
journal_directory=C:\Users\yyyy\Saved Games\Frontier Developments\Elite Dangerous\
tritium_slot=2
route_file=route.txt
Save file found. Setting up...
Beginning in 5...
Fuel: 799
Fuel: 799
Fuel: 799
Fuel: 799
Carrier destination: Col 173 Sector DH-P b24-1
Fuel: 799
Fuel: 702
Destination: Crucis Sector IH-V b2-4
Next stop: Wregoe HH-K c22-15
Beginning navigation.
Please do not change windows until navigation is complete.
ETA: 25 Jun 2023 12:10 UTC
Fuel: 702
Carrier destination: Wregoe HH-K c22-15
Fuel: 702
: 0: 5
Navigation complete. Jump occurs in : 0: 5. Counting down...
invalid literal for int() with base 10: ''
An error has occurred. Saving progress and aborting...
Message sent...
Progress saved...
Aborted.

Here the Spanch-CSV:
"System Name","Distance","Distance Remaining","Tritium in tank","Tritium in market","Fuel Used","Icy Ring","Pristine","Restock Tritium"
"Plio Eurl MD-J d9-9","0","1738.68946105743","","0","0","No","No","Yes"
"Col 173 Sector DH-P b24-1","499.85555823814","1239.37880184112","","0","100","No","No","No"
"Wregoe HH-K c22-15","499.574507432638","744.723444500751","","0","99","Yes","Yes","No"
"HIP 46484","499.70857913638","245.136929608357","","0","99","Yes","Yes","No"
"Crucis Sector IH-V b2-4","245.136929608357","0","","0","51","No","No","No"

**Comment by mck-9061** [comment]
Hi - please could you provide a screen recording of the problem happening, as well as the full latest CATS log file (feel free to blank out your name first).

**Comment by nyenyon** [comment]
[25-06-23-12-55-17-97611.txt](https://github.com/mck-9061/CATS/files/11860336/25-06-23-12-55-17-97611.txt)

this one?

**Comment by nyenyon** [comment]
Here a screenrecording and a screenshot and log:
[25-06-23-07-29-00-87334.txt](https://github.com/mck-9061/CATS/files/11860416/25-06-23-07-29-00-87334.txt) <- is empty somehow

![image](https://github.com/mck-9061/CATS/assets/137694071/09a584b8-488c-4db9-a79f-3c25f77890ef)

Video: https://drive.google.com/file/d/1EnO-yzv1tSl06f-h53L2aBzWFNlqjYus/view?usp=sharing

**Comment by mck-9061** [comment]
Hi - apologies for the late reply. I'm working on figuring out the cause of this - in the meantime, yiou can work around it by disabling OCR in the options menu.

**Comment by mck-9061** [comment]
Added a failsafe for this issue in the latest release.
