### ISSUE TITLE
Add Carrier dops an Exception

### ISSUE THREAD

**Issue by nyenyon** [mck-9061/CATS#21]
Hi,

jus installed CATS freshly on my computer. CATS starts normally. When i try to add my carrier, i get  this error after logging in at FDEV and appoveal of the accessrights:

![image](https://github.com/mck-9061/CATS/assets/137694071/b2fe8d04-b0b0-4031-a525-8efed221b12d)

![image](https://github.com/mck-9061/CATS/assets/137694071/d67c33ad-a0f9-4ae9-abe5-ff034378d5ca)

![image](https://github.com/mck-9061/CATS/assets/137694071/66d485c8-9b92-474d-93a3-10cfaff42667)

[Image redacted; contains auth key]

any idea? It worked with the 1.x version.

best regards
  nyenyon

**Comment by nyenyon** [comment]
U&redirect_uri=http%3A%2F%2Flocalhost%3A57330%2F
{
  "access_token": "eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkExMjhDQkMtSFMyNTYiLCJ6aXAiOiJERUYifQ.wFXtbjJFsPb8eNnWHRwLHdlIJYUkhn-m_-DwHzr_VWivK1C_1sRJdMW4YljjV1ycYg3vTT6ZNw-tGW6K-O_j9LEeua7uEg3i4rZAdjiuSzsecIGVNdblgzrl7FCJUZ6UiXlVyPMO_HbbojD5AWcUVdnzaE8Uga2kHy3wkffvMOeOCmpqERuUuAyvazcQ941U9mDhqWhgjRgtaZMz9jLkSzslPA_aCwiWgb3djqqhZv1ABKCjsQCj2Xh-f4psi5DUN_6ZB7xb10Wmb9NUquKkve6nyqHua5BkACr5cMO_uqwtIBtdpB-MPyUe_kbzxgtFsY1pYBSjwCpdIlCZ7fR0cg.MoVdMg6xzezcJyLHp8km0A.CJ2MWNpKeDtOXLUWTgFekoNywNPnpirFgyKNYQLPTfERUOlpmXBU8kMq0ptnWOPbWmurHyqe5asabSIrI4jKG4gDBQ1LGjdDiJma1LL5BYF4GOADU2VbbY4Qi9L1WXoe-2XDYPfPlz0eGcv9A5D-j1wNbjQ0xhB44UVBQxhFv37SbWGTMzRJOeN9IImlPkunYXW_EmuqjlwOv0_X6CQOcb5p-1lGJuwPqqI7s3e3D79-8AdJm9h-OVHG-xb-VfaItG1Om2cGYjxqZbaAzTFA3mok3T9jQfyk96d-wUkyJk8XzrTAlWcngCcN07b3s_q69fFMUEAj76tMmdVYq2TtqziWC-hqW36aHdzGNNEypqnm7kkqlWkUQkMVi4LSVul0w5G0ENeJ_ToqJR17S0cC7s3fhAvHgBN57oXHu25-gn7XZuhzfCJuDRp1-taHfsnSVGf8xzMol8dmnM0Z4uBhL4Kw4PfhMErx7N85vGuELFBR_hnP_u2SYvegMbyPx5HIzpOHZ-COhgdkK_gjNFDA1s9n6k-Gto-MN82AkXUg_w7TqbuvhzTTplXRv73pYB2N.Z2JYS60A_Ne_FKSVohWtHg",
  "token_type": "Bearer",
  "expires_in": 14399,
  "refresh_token": "0b0745f6-e6d9-4779-b93d-9459b0775d28"
}
Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
   bei System.Net.HttpWebRequest.GetResponse()
   bei MultiCarrierManager.ApiTools.CAPI.Get(String url)
   bei MultiCarrierManager.Form1.AddCarrierButton_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
https://auth.frontierstore.net/auth?scope=auth%20capi&audience=frontier&response_type=code&client_id=12ce9cc3-51c3-4daa-b07a-16d8b9c1ddec&code_challenge=F0dnWneU7VTp9xB5v52gXZs9S9U9WlEvtnHLVoPrE9Y&code_challenge_method=S256&state=ef--jMnipKo&redirect_uri=http%3A%2F%2Flocalhost%3A61244%2F

**Comment by mck-9061** [comment]
Hi - firstly, I've edited your posts to remove the auth key. This is a public issues page.

How many times did you try adding the carrier? Try removing any files in carriers/ and carriers/profiles/

**Comment by nyenyon** [comment]
i tried it several times, it never worked. the carriers/profiles folder is (still) empty.

![image](https://github.com/mck-9061/CATS/assets/137694071/b3ef806c-52b0-4de0-afd4-9d78d9751ecd)

**Comment by nyenyon** [comment]
Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
The remote server returned an error: (400) Invalid request.

this indicates a 400 error code from FDEV-server maybe...

**Comment by nyenyon** [comment]
even removing "carriers" does not help.

**Comment by mck-9061** [comment]
This is really weird... could you try an old 1.x version again and see if it still works? You can transfer over the carrier files if it does

**Comment by nyenyon** [comment]
i get the same error with v1.x (my prevous installation)...

Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
   bei System.Net.HttpWebRequest.GetResponse()
   bei MultiCarrierManager.ApiTools.CAPI.Get(String url) in H:\mcm\MultiCarrierManager\MultiCarrierManager\ApiTools\CAPI.cs:Zeile 27.
   bei MultiCarrierManager.Form1.AddCarrierButton_Click(Object sender, EventArgs e) in H:\mcm\MultiCarrierManager\MultiCarrierManager\Forms\Form1.cs:Zeile 328.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by nyenyon** [comment]
> i get the same error with v1.x (my prevous installation)...
> 
> Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung. bei System.Net.HttpWebRequest.GetResponse() bei MultiCarrierManager.ApiTools.CAPI.Get(String url) in H:\mcm\MultiCarrierManager\MultiCarrierManager\ApiTools\CAPI.cs:Zeile 27. bei MultiCarrierManager.Form1.AddCarrierButton_Click(Object sender, EventArgs e) in H:\mcm\MultiCarrierManager\MultiCarrierManager\Forms\Form1.cs:Zeile 328. bei System.Windows.Forms.Control.OnClick(EventArgs e) bei System.Windows.Forms.Button.OnClick(EventArgs e) bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent) bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks) bei System.Windows.Forms.Control.WndProc(Message& m) bei System.Windows.Forms.ButtonBase.WndProc(Message& m) bei System.Windows.Forms.Button.WndProc(Message& m) bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by nyenyon** [comment]
there one difference. i just tried to get carrierstats with EDDI. That worked perfectly. The Auth-Page is different though:
![image](https://github.com/mck-9061/CATS/assets/137694071/007242a9-4161-4185-9ab7-418a8e40a813)

here i can select epic games for login.

**Comment by mck-9061** [comment]
[patch.zip](https://github.com/mck-9061/CATS/files/12579556/patch.zip)

Please try this (just overwrite the existing EXE file in the 2.1 installation). I've changed the login page to allow for Epic accounts. I don't know why this should make a difference, but FDev have been known to do weirder things

**Comment by nyenyon** [comment]
Success:
![image](https://github.com/mck-9061/CATS/assets/137694071/c8abc325-d52d-46df-8b63-bd4ee5f37d2e)

there are still some errors.... The errors occur during "Add carrier" when ever i do "Pull Stats".

**Comment by mck-9061** [comment]
Glad that's working now, I'll get it put into a release soon.

Those errors are known about, they don't actually cause any problems - they were just for debugging purposes.
