### ISSUE TITLE
Missing Files for Build

### ISSUE THREAD

**Issue by QldAu** [mck-9061/CATS#26]
The following files are missing from the download pack, which are stopping the build

 \CATS-master\MultiCarrierManager\ApiTools\OAuth2.cs 
 \CATS-master\MultiCarrierManager\App.Config

**Comment by mck-9061** [comment]
For OAuth2.cs, please read [building.md](https://github.com/mck-9061/CATS/blob/master/building.md). Not sure why App.config was never pushed, I've pushed a commit now that adds it.
