### ISSUE TITLE
CATS errors on adding a new carrier

### ISSUE THREAD

**Issue by MegaShinySnivy** [mck-9061/CATS#27]
As stated in the title, CATS is unable to add any new carriers, as post auth screen I just get sent to a bad request, and the program hangs.

Steps to reproduce:

Open CATS
Add a new carrier
Select Steam on the auth webpage
Log in
See that you get sent to a bad request page
Program hangs

Expected outcome:
Auth succeeds and I can add a new carrier to my list

Additional information:
I am running this program through wine, however testing in a windows virtual machine nets the same result.

**Comment by mck-9061** [comment]
Hi there - as mentioned on the readme, CATS isn't currently in active development, so I'm not providing direct help at the moment. I haven't seen this error before and I'm not getting it myself. Try using a Frontier account rather than Steam
